//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NJetty.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NJetty.Resources.Mime", typeof(Mime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/h323.
        /// </summary>
        public static string _323 {
            get {
                return ResourceManager.GetString("323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/java-vm.
        /// </summary>
        public static string _class {
            get {
                return ResourceManager.GetString("class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/internet-property-stream.
        /// </summary>
        public static string acx {
            get {
                return ResourceManager.GetString("acx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        public static string ai {
            get {
                return ResourceManager.GetString("ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        public static string aif {
            get {
                return ResourceManager.GetString("aif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        public static string aifc {
            get {
                return ResourceManager.GetString("aifc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        public static string aiff {
            get {
                return ResourceManager.GetString("aiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string asc {
            get {
                return ResourceManager.GetString("asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x.ms.asf.
        /// </summary>
        public static string asf {
            get {
                return ResourceManager.GetString("asf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string asp {
            get {
                return ResourceManager.GetString("asp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string aspx {
            get {
                return ResourceManager.GetString("aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-ms-asf.
        /// </summary>
        public static string asr {
            get {
                return ResourceManager.GetString("asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-ms-asf.
        /// </summary>
        public static string asx {
            get {
                return ResourceManager.GetString("asx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/basic.
        /// </summary>
        public static string au {
            get {
                return ResourceManager.GetString("au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-msvideo.
        /// </summary>
        public static string avi {
            get {
                return ResourceManager.GetString("avi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/olescript.
        /// </summary>
        public static string axs {
            get {
                return ResourceManager.GetString("axs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string bas {
            get {
                return ResourceManager.GetString("bas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-bcpio.
        /// </summary>
        public static string bcpio {
            get {
                return ResourceManager.GetString("bcpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string bin {
            get {
                return ResourceManager.GetString("bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/bmp.
        /// </summary>
        public static string bmp {
            get {
                return ResourceManager.GetString("bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-cabinet.
        /// </summary>
        public static string cab {
            get {
                return ResourceManager.GetString("cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkiseccat.
        /// </summary>
        public static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-netcdf.
        /// </summary>
        public static string cdf {
            get {
                return ResourceManager.GetString("cdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        public static string cer {
            get {
                return ResourceManager.GetString("cer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msclip.
        /// </summary>
        public static string clp {
            get {
                return ResourceManager.GetString("clp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-cmx.
        /// </summary>
        public static string cmx {
            get {
                return ResourceManager.GetString("cmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/cis-cod.
        /// </summary>
        public static string cod {
            get {
                return ResourceManager.GetString("cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-cpio.
        /// </summary>
        public static string cpio {
            get {
                return ResourceManager.GetString("cpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/mac-compactpro.
        /// </summary>
        public static string cpt {
            get {
                return ResourceManager.GetString("cpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mscardfile.
        /// </summary>
        public static string crd {
            get {
                return ResourceManager.GetString("crd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pkix-crl.
        /// </summary>
        public static string crl {
            get {
                return ResourceManager.GetString("crl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        public static string crt {
            get {
                return ResourceManager.GetString("crt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-csh.
        /// </summary>
        public static string csh {
            get {
                return ResourceManager.GetString("csh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/css.
        /// </summary>
        public static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/comma-separated-values.
        /// </summary>
        public static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        public static string dcr {
            get {
                return ResourceManager.GetString("dcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        public static string der {
            get {
                return ResourceManager.GetString("der", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msdownload.
        /// </summary>
        public static string dll {
            get {
                return ResourceManager.GetString("dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string dms {
            get {
                return ResourceManager.GetString("dms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        public static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        public static string dot {
            get {
                return ResourceManager.GetString("dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xml-dtd.
        /// </summary>
        public static string dtd {
            get {
                return ResourceManager.GetString("dtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-dvi.
        /// </summary>
        public static string dvi {
            get {
                return ResourceManager.GetString("dvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        public static string dxr {
            get {
                return ResourceManager.GetString("dxr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        public static string eps {
            get {
                return ResourceManager.GetString("eps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-setext.
        /// </summary>
        public static string etx {
            get {
                return ResourceManager.GetString("etx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/envoy.
        /// </summary>
        public static string evy {
            get {
                return ResourceManager.GetString("evy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string exe {
            get {
                return ResourceManager.GetString("exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/andrew-inset.
        /// </summary>
        public static string ez {
            get {
                return ResourceManager.GetString("ez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/fractals.
        /// </summary>
        public static string fif {
            get {
                return ResourceManager.GetString("fif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        public static string flr {
            get {
                return ResourceManager.GetString("flr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-gtar.
        /// </summary>
        public static string gtar {
            get {
                return ResourceManager.GetString("gtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/gzip.
        /// </summary>
        public static string gz {
            get {
                return ResourceManager.GetString("gz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/gzip.
        /// </summary>
        public static string gzip {
            get {
                return ResourceManager.GetString("gzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-hdf.
        /// </summary>
        public static string hdf {
            get {
                return ResourceManager.GetString("hdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/winhlp.
        /// </summary>
        public static string hlp {
            get {
                return ResourceManager.GetString("hlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/mac-binhex40.
        /// </summary>
        public static string hqx {
            get {
                return ResourceManager.GetString("hqx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/hta.
        /// </summary>
        public static string hta {
            get {
                return ResourceManager.GetString("hta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-component.
        /// </summary>
        public static string htc {
            get {
                return ResourceManager.GetString("htc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        public static string htm {
            get {
                return ResourceManager.GetString("htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        public static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/webviewhtml.
        /// </summary>
        public static string htt {
            get {
                return ResourceManager.GetString("htt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-conference/x-cooltalk.
        /// </summary>
        public static string ice {
            get {
                return ResourceManager.GetString("ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-icon.
        /// </summary>
        public static string ico {
            get {
                return ResourceManager.GetString("ico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/ief.
        /// </summary>
        public static string ief {
            get {
                return ResourceManager.GetString("ief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/iges.
        /// </summary>
        public static string iges {
            get {
                return ResourceManager.GetString("iges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/iges.
        /// </summary>
        public static string igs {
            get {
                return ResourceManager.GetString("igs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-iphone.
        /// </summary>
        public static string iii {
            get {
                return ResourceManager.GetString("iii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-internet-signup.
        /// </summary>
        public static string ins {
            get {
                return ResourceManager.GetString("ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-internet-signup.
        /// </summary>
        public static string isp {
            get {
                return ResourceManager.GetString("isp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/java-archive.
        /// </summary>
        public static string jar {
            get {
                return ResourceManager.GetString("jar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string java {
            get {
                return ResourceManager.GetString("java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/pipeg.
        /// </summary>
        public static string jfif {
            get {
                return ResourceManager.GetString("jfif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-java-jnlp-file.
        /// </summary>
        public static string jnlp {
            get {
                return ResourceManager.GetString("jnlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        public static string jpe {
            get {
                return ResourceManager.GetString("jpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        public static string jpeg {
            get {
                return ResourceManager.GetString("jpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        public static string jpg {
            get {
                return ResourceManager.GetString("jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-javascript.
        /// </summary>
        public static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string jsp {
            get {
                return ResourceManager.GetString("jsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/midi.
        /// </summary>
        public static string kar {
            get {
                return ResourceManager.GetString("kar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-latex.
        /// </summary>
        public static string latex {
            get {
                return ResourceManager.GetString("latex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string lha {
            get {
                return ResourceManager.GetString("lha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-la-asf.
        /// </summary>
        public static string lsf {
            get {
                return ResourceManager.GetString("lsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-la-asf.
        /// </summary>
        public static string lsx {
            get {
                return ResourceManager.GetString("lsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string lzh {
            get {
                return ResourceManager.GetString("lzh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        public static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        public static string m14 {
            get {
                return ResourceManager.GetString("m14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-mpegurl.
        /// </summary>
        public static string m3u {
            get {
                return ResourceManager.GetString("m3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-man.
        /// </summary>
        public static string man {
            get {
                return ResourceManager.GetString("man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/mathml+xml.
        /// </summary>
        public static string mathml {
            get {
                return ResourceManager.GetString("mathml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msaccess.
        /// </summary>
        public static string mdb {
            get {
                return ResourceManager.GetString("mdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-me.
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/mesh.
        /// </summary>
        public static string mesh {
            get {
                return ResourceManager.GetString("mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        public static string mht {
            get {
                return ResourceManager.GetString("mht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        public static string mhtml {
            get {
                return ResourceManager.GetString("mhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/midi.
        /// </summary>
        public static string mid {
            get {
                return ResourceManager.GetString("mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/midi.
        /// </summary>
        public static string midi {
            get {
                return ResourceManager.GetString("midi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.mif.
        /// </summary>
        public static string mif {
            get {
                return ResourceManager.GetString("mif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmoney.
        /// </summary>
        public static string mny {
            get {
                return ResourceManager.GetString("mny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical/x-mdl-molfile.
        /// </summary>
        public static string mol {
            get {
                return ResourceManager.GetString("mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/quicktime.
        /// </summary>
        public static string mov {
            get {
                return ResourceManager.GetString("mov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-sgi-movie.
        /// </summary>
        public static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mpeg.
        /// </summary>
        public static string mp2 {
            get {
                return ResourceManager.GetString("mp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mpeg.
        /// </summary>
        public static string mp3 {
            get {
                return ResourceManager.GetString("mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        public static string mpa {
            get {
                return ResourceManager.GetString("mpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        public static string mpe {
            get {
                return ResourceManager.GetString("mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        public static string mpeg {
            get {
                return ResourceManager.GetString("mpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        public static string mpg {
            get {
                return ResourceManager.GetString("mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mpeg.
        /// </summary>
        public static string mpga {
            get {
                return ResourceManager.GetString("mpga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-project.
        /// </summary>
        public static string mpp {
            get {
                return ResourceManager.GetString("mpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        public static string mpv2 {
            get {
                return ResourceManager.GetString("mpv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-ms.
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/mesh.
        /// </summary>
        public static string msh {
            get {
                return ResourceManager.GetString("msh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string msi {
            get {
                return ResourceManager.GetString("msi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        public static string mvb {
            get {
                return ResourceManager.GetString("mvb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-netcdf.
        /// </summary>
        public static string nc {
            get {
                return ResourceManager.GetString("nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        public static string nws {
            get {
                return ResourceManager.GetString("nws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/oda.
        /// </summary>
        public static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.database.
        /// </summary>
        public static string odb {
            get {
                return ResourceManager.GetString("odb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.chart.
        /// </summary>
        public static string odc {
            get {
                return ResourceManager.GetString("odc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.formula.
        /// </summary>
        public static string odf {
            get {
                return ResourceManager.GetString("odf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.graphics.
        /// </summary>
        public static string odg {
            get {
                return ResourceManager.GetString("odg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.image.
        /// </summary>
        public static string odi {
            get {
                return ResourceManager.GetString("odi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.text-master.
        /// </summary>
        public static string odm {
            get {
                return ResourceManager.GetString("odm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.presentation.
        /// </summary>
        public static string odp {
            get {
                return ResourceManager.GetString("odp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.spreadsheet.
        /// </summary>
        public static string ods {
            get {
                return ResourceManager.GetString("ods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.text.
        /// </summary>
        public static string odt {
            get {
                return ResourceManager.GetString("odt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/ogg.
        /// </summary>
        public static string ogg {
            get {
                return ResourceManager.GetString("ogg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.chart-template.
        /// </summary>
        public static string otc {
            get {
                return ResourceManager.GetString("otc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.formula-template.
        /// </summary>
        public static string otf {
            get {
                return ResourceManager.GetString("otf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.graphics-template.
        /// </summary>
        public static string otg {
            get {
                return ResourceManager.GetString("otg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.text-web.
        /// </summary>
        public static string oth {
            get {
                return ResourceManager.GetString("oth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.image-template.
        /// </summary>
        public static string oti {
            get {
                return ResourceManager.GetString("oti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.presentation-template.
        /// </summary>
        public static string otp {
            get {
                return ResourceManager.GetString("otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.spreadsheet-template.
        /// </summary>
        public static string ots {
            get {
                return ResourceManager.GetString("ots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.oasis.opendocument.text-template.
        /// </summary>
        public static string ott {
            get {
                return ResourceManager.GetString("ott", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pkcs10.
        /// </summary>
        public static string p10 {
            get {
                return ResourceManager.GetString("p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs12.
        /// </summary>
        public static string p12 {
            get {
                return ResourceManager.GetString("p12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certificates.
        /// </summary>
        public static string p7b {
            get {
                return ResourceManager.GetString("p7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-mime.
        /// </summary>
        public static string p7c {
            get {
                return ResourceManager.GetString("p7c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-mime.
        /// </summary>
        public static string p7m {
            get {
                return ResourceManager.GetString("p7m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certreqresp.
        /// </summary>
        public static string p7r {
            get {
                return ResourceManager.GetString("p7r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-signature.
        /// </summary>
        public static string p7s {
            get {
                return ResourceManager.GetString("p7s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-bitmap.
        /// </summary>
        public static string pbm {
            get {
                return ResourceManager.GetString("pbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical/x-pdb.
        /// </summary>
        public static string pdb {
            get {
                return ResourceManager.GetString("pdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs12.
        /// </summary>
        public static string pfx {
            get {
                return ResourceManager.GetString("pfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-graymap.
        /// </summary>
        public static string pgm {
            get {
                return ResourceManager.GetString("pgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-chess-pgn.
        /// </summary>
        public static string pgn {
            get {
                return ResourceManager.GetString("pgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/ynd.ms-pkipko.
        /// </summary>
        public static string pko {
            get {
                return ResourceManager.GetString("pko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        public static string pma {
            get {
                return ResourceManager.GetString("pma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        public static string pmc {
            get {
                return ResourceManager.GetString("pmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        public static string pml {
            get {
                return ResourceManager.GetString("pml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        public static string pmr {
            get {
                return ResourceManager.GetString("pmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        public static string pmw {
            get {
                return ResourceManager.GetString("pmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/png.
        /// </summary>
        public static string png {
            get {
                return ResourceManager.GetString("png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-anymap.
        /// </summary>
        public static string pnm {
            get {
                return ResourceManager.GetString("pnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string pot {
            get {
                return ResourceManager.GetString("pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-pixmap.
        /// </summary>
        public static string ppm {
            get {
                return ResourceManager.GetString("ppm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string pps {
            get {
                return ResourceManager.GetString("pps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string ppt {
            get {
                return ResourceManager.GetString("ppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pics-rules.
        /// </summary>
        public static string prf {
            get {
                return ResourceManager.GetString("prf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        public static string ps {
            get {
                return ResourceManager.GetString("ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mspublisher.
        /// </summary>
        public static string pub {
            get {
                return ResourceManager.GetString("pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/quicktime.
        /// </summary>
        public static string qt {
            get {
                return ResourceManager.GetString("qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-pn-realaudio.
        /// </summary>
        public static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-pn-realaudio.
        /// </summary>
        public static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-cmu-raster.
        /// </summary>
        public static string ras {
            get {
                return ResourceManager.GetString("ras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/rdf+xml.
        /// </summary>
        public static string rdf {
            get {
                return ResourceManager.GetString("rdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-rgb.
        /// </summary>
        public static string rgb {
            get {
                return ResourceManager.GetString("rgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-pn-realaudio.
        /// </summary>
        public static string rm {
            get {
                return ResourceManager.GetString("rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mid.
        /// </summary>
        public static string rmi {
            get {
                return ResourceManager.GetString("rmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        public static string roff {
            get {
                return ResourceManager.GetString("roff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-rpm.
        /// </summary>
        public static string rpm {
            get {
                return ResourceManager.GetString("rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/rtf.
        /// </summary>
        public static string rtf {
            get {
                return ResourceManager.GetString("rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/richtext.
        /// </summary>
        public static string rtx {
            get {
                return ResourceManager.GetString("rtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msschedule.
        /// </summary>
        public static string scd {
            get {
                return ResourceManager.GetString("scd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/scriptlet.
        /// </summary>
        public static string sct {
            get {
                return ResourceManager.GetString("sct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/java-serialized-object.
        /// </summary>
        public static string ser {
            get {
                return ResourceManager.GetString("ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/set-payment-initiation.
        /// </summary>
        public static string setpay {
            get {
                return ResourceManager.GetString("setpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/set-registration-initiation.
        /// </summary>
        public static string setreg {
            get {
                return ResourceManager.GetString("setreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/sgml.
        /// </summary>
        public static string sgm {
            get {
                return ResourceManager.GetString("sgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/sgml.
        /// </summary>
        public static string sgml {
            get {
                return ResourceManager.GetString("sgml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sh.
        /// </summary>
        public static string sh {
            get {
                return ResourceManager.GetString("sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-shar.
        /// </summary>
        public static string shar {
            get {
                return ResourceManager.GetString("shar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/mesh.
        /// </summary>
        public static string silo {
            get {
                return ResourceManager.GetString("silo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-stuffit.
        /// </summary>
        public static string sit {
            get {
                return ResourceManager.GetString("sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-koan.
        /// </summary>
        public static string skd {
            get {
                return ResourceManager.GetString("skd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-koan.
        /// </summary>
        public static string skm {
            get {
                return ResourceManager.GetString("skm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-koan.
        /// </summary>
        public static string skp {
            get {
                return ResourceManager.GetString("skp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-koan.
        /// </summary>
        public static string skt {
            get {
                return ResourceManager.GetString("skt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/smil.
        /// </summary>
        public static string smi {
            get {
                return ResourceManager.GetString("smi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/smil.
        /// </summary>
        public static string smil {
            get {
                return ResourceManager.GetString("smil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/basic.
        /// </summary>
        public static string snd {
            get {
                return ResourceManager.GetString("snd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certificates.
        /// </summary>
        public static string spc {
            get {
                return ResourceManager.GetString("spc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-futuresplash.
        /// </summary>
        public static string spl {
            get {
                return ResourceManager.GetString("spl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-wais-source.
        /// </summary>
        public static string src {
            get {
                return ResourceManager.GetString("src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkicertstore.
        /// </summary>
        public static string sst {
            get {
                return ResourceManager.GetString("sst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkistl.
        /// </summary>
        public static string stl {
            get {
                return ResourceManager.GetString("stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        public static string stm {
            get {
                return ResourceManager.GetString("stm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sv4cpio.
        /// </summary>
        public static string sv4cpio {
            get {
                return ResourceManager.GetString("sv4cpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sv4crc.
        /// </summary>
        public static string sv4crc {
            get {
                return ResourceManager.GetString("sv4crc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/svg+xml.
        /// </summary>
        public static string svg {
            get {
                return ResourceManager.GetString("svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-shockwave-flash.
        /// </summary>
        public static string swf {
            get {
                return ResourceManager.GetString("swf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        public static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tar.
        /// </summary>
        public static string tar {
            get {
                return ResourceManager.GetString("tar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-gtar.
        /// </summary>
        public static string tar_gz {
            get {
                return ResourceManager.GetString("tar.gz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tcl.
        /// </summary>
        public static string tcl {
            get {
                return ResourceManager.GetString("tcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tex.
        /// </summary>
        public static string tex {
            get {
                return ResourceManager.GetString("tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-texinfo.
        /// </summary>
        public static string texi {
            get {
                return ResourceManager.GetString("texi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-texinfo.
        /// </summary>
        public static string texinfo {
            get {
                return ResourceManager.GetString("texinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-gtar.
        /// </summary>
        public static string tgz {
            get {
                return ResourceManager.GetString("tgz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        public static string tif {
            get {
                return ResourceManager.GetString("tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        public static string tiff {
            get {
                return ResourceManager.GetString("tiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        public static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msterminal.
        /// </summary>
        public static string trm {
            get {
                return ResourceManager.GetString("trm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/tab-separated-values.
        /// </summary>
        public static string tsv {
            get {
                return ResourceManager.GetString("tsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/iuls.
        /// </summary>
        public static string uls {
            get {
                return ResourceManager.GetString("uls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-ustar.
        /// </summary>
        public static string ustar {
            get {
                return ResourceManager.GetString("ustar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-cdlink.
        /// </summary>
        public static string vcd {
            get {
                return ResourceManager.GetString("vcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-vcard.
        /// </summary>
        public static string vcf {
            get {
                return ResourceManager.GetString("vcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/vrml.
        /// </summary>
        public static string vrml {
            get {
                return ResourceManager.GetString("vrml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/voicexml+xml.
        /// </summary>
        public static string vxml {
            get {
                return ResourceManager.GetString("vxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-wav.
        /// </summary>
        public static string wav {
            get {
                return ResourceManager.GetString("wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/vnd.wap.wbmp.
        /// </summary>
        public static string wbmp {
            get {
                return ResourceManager.GetString("wbmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        public static string wcm {
            get {
                return ResourceManager.GetString("wcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        public static string wdb {
            get {
                return ResourceManager.GetString("wdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        public static string wks {
            get {
                return ResourceManager.GetString("wks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmetafile.
        /// </summary>
        public static string wmf {
            get {
                return ResourceManager.GetString("wmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/vnd.wap.wml.
        /// </summary>
        public static string wml {
            get {
                return ResourceManager.GetString("wml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.wap.wmlc.
        /// </summary>
        public static string wmlc {
            get {
                return ResourceManager.GetString("wmlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/vnd.wap.wmlscript.
        /// </summary>
        public static string wmls {
            get {
                return ResourceManager.GetString("wmls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.wap.wmlscriptc.
        /// </summary>
        public static string wmlsc {
            get {
                return ResourceManager.GetString("wmlsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        public static string wps {
            get {
                return ResourceManager.GetString("wps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mswrite.
        /// </summary>
        public static string wri {
            get {
                return ResourceManager.GetString("wri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model/vrml.
        /// </summary>
        public static string wrl {
            get {
                return ResourceManager.GetString("wrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        public static string wrz {
            get {
                return ResourceManager.GetString("wrz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.wap.wtls-ca-certificate.
        /// </summary>
        public static string wtls_ca_certificate {
            get {
                return ResourceManager.GetString("wtls-ca-certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        public static string xaf {
            get {
                return ResourceManager.GetString("xaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xbitmap.
        /// </summary>
        public static string xbm {
            get {
                return ResourceManager.GetString("xbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xhtml+xml.
        /// </summary>
        public static string xht {
            get {
                return ResourceManager.GetString("xht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xhtml+xml.
        /// </summary>
        public static string xhtml {
            get {
                return ResourceManager.GetString("xhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xla {
            get {
                return ResourceManager.GetString("xla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xlc {
            get {
                return ResourceManager.GetString("xlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xlm {
            get {
                return ResourceManager.GetString("xlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xls {
            get {
                return ResourceManager.GetString("xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xlt {
            get {
                return ResourceManager.GetString("xlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string xlw {
            get {
                return ResourceManager.GetString("xlw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xml.
        /// </summary>
        public static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        public static string xof {
            get {
                return ResourceManager.GetString("xof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xpixmap.
        /// </summary>
        public static string xpm {
            get {
                return ResourceManager.GetString("xpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xml.
        /// </summary>
        public static string xsl {
            get {
                return ResourceManager.GetString("xsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xslt+xml.
        /// </summary>
        public static string xslt {
            get {
                return ResourceManager.GetString("xslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.mozilla.xul+xml.
        /// </summary>
        public static string xul {
            get {
                return ResourceManager.GetString("xul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xwindowdump.
        /// </summary>
        public static string xwd {
            get {
                return ResourceManager.GetString("xwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical/x-xyz.
        /// </summary>
        public static string xyz {
            get {
                return ResourceManager.GetString("xyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/compress.
        /// </summary>
        public static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/zip.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
